### ISSUE TITLE
pm2 service started on Ubuntu

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/role_nodejs#2]
Node is a popular language, once installed Node, suggest we can install some popular frameworks  by on need.
e.g
```
nodejs_install_apps:
  - express
  - vue
  - react
```

**Comment by qiaofeng1227** [comment]
there is a error in ubuntu when pm2 service started.
```
2020-12-23T09:45:53: PM2 error: Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-12-23T09:45:53: PM2 error: Cancelling versioning data parsing
```

**Comment by qiaofeng1227** [comment]
```
root@iZj6c30mvjuk3kmz7sbby6Z:~# systemctl status pm2-root
● pm2-root.service - PM2 process manager
   Loaded: loaded (/etc/systemd/system/pm2-root.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Fri 2021-04-23 19:27:46 CST; 1min 16s ago
     Docs: https://pm2.keymetrics.io/
  Process: 2128 ExecStop=/opt/nvm/versions/node/v13.14.0/lib/node_modules/pm2/bin/pm2 kill (code=exited, status=0/SUCCESS)
  Process: 660 ExecStart=/opt/nvm/versions/node/v13.14.0/lib/node_modules/pm2/bin/pm2 resurrect (code=exited, status=0/SUCCESS)
 Main PID: 1144 (code=exited, status=0/SUCCESS)

Apr 23 19:26:20 iZj6c30mvjuk3kmz7sbby6Z pm2[660]: │ id  │ name       │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
Apr 23 19:26:20 iZj6c30mvjuk3kmz7sbby6Z pm2[660]: ├─────┼────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
Apr 23 19:26:20 iZj6c30mvjuk3kmz7sbby6Z pm2[660]: │ 0   │ express    │ default     │ 0.0.0   │ fork    │ 1373     │ 0s     │ 0    │ online    │ 0%       │ 26.3mb   │ root     │ disabled │
Apr 23 19:26:20 iZj6c30mvjuk3kmz7sbby6Z pm2[660]: └─────┴────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Apr 23 19:26:20 iZj6c30mvjuk3kmz7sbby6Z systemd[1]: pm2-root.service: Supervising process 1144 which is not our child. We'll most likely not notice when it exits.
Apr 23 19:26:20 iZj6c30mvjuk3kmz7sbby6Z systemd[1]: Started PM2 process manager.
Apr 23 19:27:46 iZj6c30mvjuk3kmz7sbby6Z pm2[2128]: [PM2] Applying action deleteProcessId on app [all](ids: [ 0 ])
Apr 23 19:27:46 iZj6c30mvjuk3kmz7sbby6Z pm2[2128]: [PM2] [express](0) ✓
Apr 23 19:27:46 iZj6c30mvjuk3kmz7sbby6Z pm2[2128]: [PM2] [v] All Applications Stopped
Apr 23 19:27:46 iZj6c30mvjuk3kmz7sbby6Z pm2[2128]: [PM2] [v] PM2 Daemon Stopped
```

**Comment by qiaofeng1227** [comment]
ubuntu18.04 only run  role_nodejs, restart the sever, OK.
Test by **Tencent test server** or start by a image on Amazon, error.

**Comment by chendelin1982** [comment]
1. Add the below command to /home/*/.bashrc by init.sh, all no-root user can use `nvm`, 'pm2', 'node' directly
```
export NVM_DIR="/opt/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

2. Add the blow commands to init.sh and init-apps.service can manage pm2
```
sudo su - -c "source /opt/nvm/nvm.sh&&pm2 delete www"
sudo su - -c "source /opt/nvm/nvm.sh&&pm2 start /data/wwwroot/express/bin/www --watch&&pm2 save"
```
